[project]
name = "project-orion"
version = "0.1.0"
description = "A laser turret system that tracks hand movements in real-time to highlight points on a wall."
readme = "README.md"
requires-python = ">=3.9, <=3.13"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]
